### ISSUE TITLE
Replacing login.css / custom theming

### ISSUE THREAD

**Issue by derpdead** [InseeFrLab/keycloakify#112]
Hello,

I do have a question about theme customisation using the [look and feel demo app](https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel). 

The `import { defaultKcProps } from 'keycloakify'` is returning the `styles` with `login.css` value that points to the generated file in `build_keycloak/src/main/resources/theme/custom-theme/login/resources/css/login.css`. 

1. Is there any place in the **src** / **public** where we put our `login.css` which will overwrite the one generated by default? 
2. If not, shall we remove the import from `styles` in the `defaultKcProps` and then implement our custom css with import directly to the page component that we will use in `KcApp` ?

**Comment by garronej** [comment]
Hi @derpdead,  

> Is there any place in the src / public where we put our login.css which will overwrite the one generated by default?  

No there is not   

> If not, shall we remove the import from styles in the defaultKcProps and then implement our custom css with import directly to the page component that we will use in KcApp ?   

You definitely can break free from the default theme and implement everything from scratch but I would recommend to leave the defaults and instead overwrite by adding custom classes instead of replacing the existing ones.    

Anyways here is a production example:  
code:  https://github.com/InseeFrLab/onyxia-web/tree/main/src/ui/components/KcApp  
app live:  https://datalab.sspcloud.fr/home   

And another one:  
code: https://github.com/etalab/sill-web/tree/main/src/ui/components/KcApp   
app live:  https://sill.etalab.gouv.fr/   

Happy hacking
