### ISSUE TITLE
All available screens for designers

### ISSUE THREAD

**Issue by mariusz-kraj** [InseeFrLab/keycloakify#125]
Hi,

I wonder if there is any way to get screenshots of all available pages of the theme that we could pass to the design team to prepare the complete design?

**Comment by garronej** [comment]
Hi @mariusz-kraj,  
Unfortunately there isn't any I am aware of.  
Only thing I can suggest is to [render every pages with mock data](https://docs.keycloakify.dev/developpement#seeing-the-result-live) and take screenshots using [the demo setup](https://github.com/garronej/keycloakify-demo-app), it shouldn't take too long.  
If you actually do it I would highly appreciate you share them here so I can include them in the documentation.  

The problem is that depending of how your Keycloak server is configure the page will be radically different.  

Best

**Comment by Ann2827** [comment]
Hi @mariusz-kraj, 
We also had a need to submit the forms for designer review and I made a very convenient demo stand.
If I need to change the design on a certain form, I don't need to change the mocks anymore. The stand is also convenient if you need to build several themes.

Unfortunately, my repository is private. It will take me a little time to make an example on github.

I'll attach a link here later.

<img width="1442" alt="Снимок экрана 2022-07-02 в 10 29 07" src="https://user-images.githubusercontent.com/32645809/176991164-2c1fffc8-8d7e-49b3-9e67-46af619d7a14.png">

**Comment by garronej** [comment]
@Ann2827 this is so nice 😍  
It would be awesome if this could be open-sourced and integrated to Keycloakify

**Comment by mariusz-kraj** [comment]
Hi @Ann2827 can you let us know when you will be able to make it public? This awesome work you did :)

**Comment by lordvlad** [comment]
we could try and set up storybook 🤔

**Comment by lordvlad** [comment]
first shot https://github.com/InseeFrLab/keycloakify/issues/125

**Comment by lordvlad** [comment]
for this to be really usefull, we'll need to extend the starter with all pages 🧑‍🏭

**Comment by lordvlad** [comment]
https://starter.keycloakify.dev/storybook

**Comment by mariusz-kraj** [comment]
This is awesome! Thank you :)
