### ISSUE TITLE
Provide custom variables to email template

### ISSUE THREAD

**Issue by ghost** [InseeFrLab/keycloakify#129]
Hi there! 

I am developing multitenant system and i need to send different emails depend on user role.
Is it able to provide custom variables to email template or generate emails and then pass it to keycloak? 
Also i am a little bit confused, i saw keycloak source code and there they pass only one useful attribute (user), but there only first name, last name and email, but i still need user.roles.

Wish someone will help with this.

**Comment by garronej** [comment]
Hi @umbrellait-alexander-serkov,  
Sorry I didn't respond because I did almost no experimentation with email.  
Your usecase seems legit though.  
If you are feeling advanturous you can copy pass [the ftl script that transform the ftl context into a JS script that create an object](https://github.com/InseeFrLab/keycloakify/blob/main/src/bin/build-keycloak-theme/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl) and see what is actually made available by keycloak.  

I would be interested to see your findings.
