### ISSUE TITLE
Feature request: Ability to customise the "account" theme

### ISSUE THREAD

**Issue by buffless-matt** [InseeFrLab/keycloakify#158]
Similar to the request of #9 and the [work that was done for it](https://github.com/InseeFrLab/keycloakify/commit/efde71d07cebb707e9bce011c41e0aefd1bd7643), but for the "account" theme: 
![image](https://user-images.githubusercontent.com/96466754/184796144-7e2f698f-dbd4-48fc-a3f8-85513a870851.png)

**Comment by marziman** [comment]
That would be really good. Currently we are kinda mixing keycloakify style with the old KC custimization style. Account theme, similiar to all user facing pages would be great if supported. Thats the main reason why folks use keycloakify, I believe.

**Comment by JoJk0** [comment]
That limitation is a show-stopper for me. I wish I've read the "Limitations" section before I started development with Keycloakify.

**Comment by alessandro308** [comment]
I don't understand if it's possible to generate Account as custom page or not at all

**Comment by garronej** [comment]
Hi @alessandro308,  
No, not yet.  
Account theme support is the next item in my TODO list for Keycloakify but for the moment it's not supported at all.

**Comment by jspizziri** [comment]
@garronej , I'm potentially interested in contributing some code to this effort.

Would you be able to provide some guidance and a status of if anything has been done yet or not?

Thanks!

**Comment by garronej** [comment]
Hello @jspizziri,  

Thanks for your willingness to contribute!   
Nothing has been done yet.  
If you like we can schedule a call to help you get started.

**Comment by jspizziri** [comment]
@garronej yeah, that'd be great. You can DM me on discord if that works (`jspizziri#1826`), otherwise LMK what form of communication works best for you.

**Comment by jspizziri** [comment]
@garronej is the task effectively converting all the account page `ftl`'s into corresponding react components (similar to how one would create a custom page) and adding it to the `KcApp.tsx`'s switch statement?

**Comment by garronej** [comment]
Hi @jspizziri,  

Okay so there are three main tasks:  

1) Making Keycloakify bundle an account theme.  

<img width="861" alt="image" src="https://user-images.githubusercontent.com/6702424/220795088-91ce24fe-c4fd-4b2e-9444-c900874be3d3.png">

This is highly technical but not very time consuming.  

2) Translating the built-in "Keycloak" .ftl pages into React so that people don’t have to implement from scratch.  

For example, check out a PR that translate [`login-idp-link-email.ftl`](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-idp-link-email.ftl).  

The job would be to translate these pages:  https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/base/account  

We can release the support before having all the pages, it's possible to fallback to the "Keycloak" theme.  

This task is not complicated but very time consuming.  

3) Updating the documentation.  

There is a "edit on github" link on every page of [The documentation website](https://docs.keycloakify.dev/).  


I can commit to implement 1) this week and if you were willing to help with 2).  
How does it sound?

**Comment by jspizziri** [comment]
@garronej sorry for changing direction here, but in the intervening time I created [a super simple template project doing it the "old school" way](https://github.com/5-stones/keycloak-theme). For right now, it's the fastest path to get to production, but perhaps I'll revisit this thread someday.

Thanks again for your help!

**Comment by garronej** [comment]
@jspizziri Ok, understandable.  

In the meantime if anyone is willing to help on this please let me know.  
This is the kind of PR that you can do while watching netflix.

**Comment by garronej** [comment]
This is going to be moving forward very soon, you can all thanks [Elgato](https://twitter.com/elgato) that decided to get involved.

**Comment by garronej** [comment]
The feature is implemented and a release candidate for v7 has been published.  
Next step is to document and update the starter.
