### ISSUE TITLE
Customize E-mails with react or ftl only?

### ISSUE THREAD

**Issue by Ediste** [InseeFrLab/keycloakify#223]
I have already checked the Advanced Starter and the documentation but it is unclear to me whether it is also possible to write React code for the e-mails or does keycloakify not yet support this and must the existing ftl files (in the keycloak_email folder) be edited manually for this? If so, is there an example of how to do this?

**Comment by garronej** [comment]
Hello @Ediste,  
> is also possible to write React code for the e-mails  

No, not yet.  

> n the keycloak_email folder) be edited manually for this  

You can edit the files in the `keycloak_email`.  

> If so, is there an example of how to do this?  

Since there is nothing specific to keycloakify, you can refer to the official Keycloak documentation.  Or by deduction by looking at the `keycloak_email`.  

PS: Maybe it's not up to you to take this kind of decisions but I'd advice against sending heavily customized HTML email for things like password recovery or two factor authentication codes (the emails Keycloak typicaly sends).  
By adding HTML you drastically increace the probability of your email ending up in spam box and many email client will block the assets.
